name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    #- name: Install Playwright Browsers
    #  run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: playwright test page-object-model/E2E/Tests/Login.spec.ts --headed --project=chromium && npx playwright show-report
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
